import { lazy } from 'react';
import { Landmark } from 'lucide-react';
import type { ModuleManifest } from '../_types';

const DzBtphExchangeModule = lazy(() => import('./DzBtphExchangeModule'));

export const manifest: ModuleManifest = {
  id: 'dz-btph-exchange',
  name: 'Algérie BTPH — BPU / DQE Exchange',
  description: 'Import and export BOQ in Algerian BPU/DQE format (8 Lots BTPH, DZD, TVA LF2026) — Décret 15-247',
  version: '1.0.0',
  icon: Landmark,
  category: 'regional',
  defaultEnabled: false,
  depends: ['boq'],
  routes: [
    {
      path: '/dz-btph-exchange',
      title: 'Algérie BTPH Exchange',
      component: DzBtphExchangeModule,
    },
  ],
  navItems: [
    {
      labelKey: 'nav.dz_btph_exchange',
      to: '/dz-btph-exchange',
      icon: Landmark,
      group: 'regional',
      advancedOnly: true,
    },
  ],
  searchEntries: [
    {
      label: 'Algérie BTPH BPU / DQE Import / Export',
      path: '/dz-btph-exchange',
      keywords: ['algeria', 'dz', 'btph', 'bpu', 'dqe', 'bordereau', 'cps', 'cctp', '15-247', 'lf2026', 'cacoba', 'rpa99', 'wilaya', 'dzd', 'cnpc', 'etb', 'soumission', 'decompte', 'dgd'],
    },
  ],
  translations: {
    en: {
      'nav.dz_btph_exchange': 'Algérie BTPH Exchange',
      'dz_btph.title': 'Algérie BTPH — BPU / DQE Import / Export',
      'dz_btph.subtitle': 'Exchange BOQ in Algerian BPU/DQE format (8 Lots BTPH, DZD, TVA LF2026 — Décret 15-247)',
      'dz_btph.tab_import': 'Import',
      'dz_btph.tab_export': 'Export',
      'dz_btph.import_complete': 'BPU/DQE import complete',
      'dz_btph.export_complete': 'BPU/DQE export complete',
      'dz_btph.info': 'BPU (Bordereau des Prix Unitaires) + DQE (Détail Quantitatif Estimatif) are the Algerian BOQ standards per Décret 15-247 (Code des Marchés Publics). Works are organised by 8 Lots BTPH with DZD currency, TVA 19%/9% (LF2026), Retenue 5% and CACOBATPH 12.21%.',
      'dz_btph.drop_file': 'Drop a BPU/DQE file here (Excel or CSV), or',
      'dz_btph.browse': 'Browse files',
      'dz_btph.bpu_format': 'BPU (Unit Prices)',
      'dz_btph.dqe_format': 'DQE (Quantified)',
      'dz_btph.formats_hint': 'Supported: .csv, .tsv, .xlsx (DZ BPU/DQE formatted BOQ)',
      'dz_btph.preview': 'Preview',
      'dz_btph.positions': 'positions',
      'dz_btph.positions_found': 'positions found',
      'dz_btph.show_less': 'Show less',
      'dz_btph.show_all': 'Show all',
      'dz_btph.target_boq': 'Import Target',
      'dz_btph.select_boq': 'Select BOQ',
      'dz_btph.importing': 'Importing...',
      'dz_btph.import_btn': 'Import positions',
      'dz_btph.import_failed': 'BPU/DQE import failed',
      'dz_btph.positions_imported': 'positions imported',
      'dz_btph.parsed_ok': 'File parsed successfully',
      'dz_btph.parse_error': 'No positions found. Ensure the file is a valid DZ BPU/DQE spreadsheet (CSV or Excel).',
      'dz_btph.parse_error_generic': 'Failed to parse the BPU/DQE file.',
      'dz_btph.source_boq': '1. Select BOQ to Export',
      'dz_btph.export_format': 'Format',
      'dz_btph.export_summary': '2. Export Summary',
      'dz_btph.hide_preview': 'Hide preview',
      'dz_btph.show_preview': 'Show preview',
      'dz_btph.sections': 'Lots',
      'dz_btph.format_label': 'Format',
      'dz_btph.prices': 'Prices',
      'dz_btph.export_btn': 'Export as BPU/DQE CSV',
      'dz_btph.export_failed': 'BPU/DQE export failed',
      'dz_btph.no_positions': 'This BOQ has no positions to export.',
      'dz_btph.print_btn': 'Print PDF',
      'dz_btph.lot': 'Lot',
      'dz_btph.currency': 'Currency',
      'dz_btph.validation_hint': 'DZ BTPH validation (dz_btph) checks TVA 19%/9%, TAP suppression, Lot 01-08 and DZD currency.',
    },
    fr: {
      'nav.dz_btph_exchange': 'Échange BTPH Algérie',
      'dz_btph.title': 'Algérie BTPH — Import / Export BPU / DQE',
      'dz_btph.subtitle': 'Échanger les DQE au format BPU/DQE algérien (8 Lots BTPH, DZD, TVA LF2026 — Décret 15-247)',
      'dz_btph.tab_import': 'Importer',
      'dz_btph.tab_export': 'Exporter',
      'dz_btph.import_complete': 'Import BPU/DQE terminé',
      'dz_btph.export_complete': 'Export BPU/DQE terminé',
      'dz_btph.drop_file': 'Glissez un fichier BPU/DQE ici (Excel ou CSV), ou',
      'dz_btph.browse': 'Parcourir',
      'dz_btph.bpu_format': 'BPU (Prix unitaires)',
      'dz_btph.dqe_format': 'DQE (Quantitatif)',
      'dz_btph.info': 'Le BPU (Bordereau des Prix Unitaires) + DQE (Détail Quantitatif Estimatif) sont les formats algériens du Décret 15-247 (Code des Marchés Publics). Travaux en 8 Lots BTPH, devise DZD, TVA 19%/9% (LF2026), Retenue 5% et CACOBATPH 12,21%.',
      'dz_btph.formats_hint': 'Formats acceptés : .csv, .tsv, .xlsx (BOQ au format DZ BPU/DQE)',
      'dz_btph.preview': 'Aperçu',
      'dz_btph.positions': 'postes',
      'dz_btph.positions_found': 'postes trouvés',
      'dz_btph.show_less': 'Voir moins',
      'dz_btph.show_all': 'Voir tout',
      'dz_btph.target_boq': 'Cible d’import',
      'dz_btph.select_boq': 'Sélectionner le DQE',
      'dz_btph.importing': 'Import en cours...',
      'dz_btph.import_btn': 'Importer les postes',
      'dz_btph.import_failed': 'Échec de l’import BPU/DQE',
      'dz_btph.positions_imported': 'postes importés',
      'dz_btph.parsed_ok': 'Fichier analysé avec succès',
      'dz_btph.parse_error': 'Aucun poste trouvé. Vérifiez que le fichier est un BPU/DQE DZ valide (CSV ou Excel).',
      'dz_btph.parse_error_generic': 'Échec de l’analyse du fichier BPU/DQE.',
      'dz_btph.source_boq': '1. Sélectionner le DQE à exporter',
      'dz_btph.export_format': 'Format',
      'dz_btph.export_summary': '2. Résumé de l’export',
      'dz_btph.hide_preview': 'Masquer l’aperçu',
      'dz_btph.show_preview': 'Afficher l’aperçu',
      'dz_btph.sections': 'Lots',
      'dz_btph.format_label': 'Format',
      'dz_btph.prices': 'Prix',
      'dz_btph.export_btn': 'Exporter en CSV BPU/DQE',
      'dz_btph.export_failed': 'Échec de l’export BPU/DQE',
      'dz_btph.no_positions': 'Ce DQE ne contient aucun poste à exporter.',
      'dz_btph.print_btn': 'Imprimer PDF',
      'dz_btph.lot': 'Lot',
      'dz_btph.currency': 'Devise',
      'dz_btph.validation_hint': 'La validation DZ BTPH (dz_btph) vérifie TVA 19%/9%, suppression TAP, Lot 01-08 et devise DZD.',
    },
    de: {
      'nav.dz_btph_exchange': 'DZ BTPH Austausch',
      'dz_btph.title': 'Algerien BTPH — BPU / DQE Import / Export',
      'dz_btph.subtitle': 'LV-Daten im algerischen BPU/DQE-Format austauschen (8 Lots BTPH, DZD, TVA LF2026 — Décret 15-247)',
      'dz_btph.tab_import': 'Importieren',
      'dz_btph.tab_export': 'Exportieren',
      'dz_btph.import_complete': 'BPU/DQE-Import abgeschlossen',
      'dz_btph.export_complete': 'BPU/DQE-Export abgeschlossen',
    },
    ru: {
      'nav.dz_btph_exchange': 'DZ BTPH Obmen',
      'dz_btph.title': 'Alzhir BTPH — Import / Eksport BPU / DQE',
      'dz_btph.subtitle': 'Obmen vedomostyu v formate BPU/DQE (8 Lots BTPH, DZD, TVA LF2026 — Décret 15-247)',
      'dz_btph.tab_import': 'Import',
      'dz_btph.tab_export': 'Eksport',
      'dz_btph.import_complete': 'Import BPU/DQE zavershjon',
      'dz_btph.export_complete': 'Eksport BPU/DQE zavershjon',
    },
    ar: {
      'nav.dz_btph_exchange': 'تبادل BTPH الجزائر',
      'dz_btph.title': 'الجزائر BTPH — استيراد / تصدير BPU / DQE',
      'dz_btph.subtitle': 'تبادل الكشوف بصيغة BPU/DQE الجزائرية (8 حصص BTPH، دج، TVA LF2026 — مرسوم 15-247)',
      'dz_btph.tab_import': 'استيراد',
      'dz_btph.tab_export': 'تصدير',
      'dz_btph.import_complete': 'اكتمل استيراد BPU/DQE',
      'dz_btph.export_complete': 'اكتمل تصدير BPU/DQE',
      'dz_btph.drop_file': 'أسقط ملف BPU/DQE هنا (Excel أو CSV)، أو',
      'dz_btph.browse': 'تصفح',
      'dz_btph.preview': 'معاينة',
      'dz_btph.positions': 'بنود',
      'dz_btph.target_boq': 'وجهة الاستيراد',
      'dz_btph.select_boq': 'اختر الكشف',
      'dz_btph.importing': 'جاري الاستيراد...',
      'dz_btph.import_btn': 'استيراد البنود',
      'dz_btph.lot': 'حصة',
      'dz_btph.currency': 'العملة',
    },
  },
};
